container:
  image: cirrusci/flutter:latest

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - flutter test
    - flutter doctor
    - flutter -v build apk --debug
#    - flutter -v build ios --debug --no-codesign