container:
  image: cirrusci/flutter:latest

#test_task:
#  pub_cache:
#    folder: ~/.pub-cache
#  test_script:
#    - flutter test
#    - flutter doctor
#  build_script:
#    - flutter -v build apk --debug

task:
  pub_cache:
    folder: ~/.pub-cache
  env:
    # Name the SDK directory to include a space so that we constantly
    # test path names with spaces in them.
    CIRRUS_WORKING_DIR: "/tmp/flutter sdk"
  osx_instance:
    image: mojave-xcode-10.1
  setup_script:
    - bin/flutter config --no-analytics
    - bin/flutter doctor -v
    - bin/flutter update-packages
  build_script:
    - flutter -v build apk --debug
    - flutter -v build ios --debug --no-codesign