container:
  image: cirrusci/flutter:latest

osx_instance:
  image: mojave-xcode-10.2
#    image: mojave-xcode-10.2-flutter

task:
  script: echo "Hello World from macOS!"
  setup_script:
    - system_profiler SPSoftwareDataType
    - sw_vers
    - defaults read loginwindow SystemVersionStampAsString

#test_task:
#  pub_cache:
#    folder: ~/.pub-cache
#  setup_script:
#    - flutter doctor -v
#  test_script:
#    - flutter test --coverage
#  build_script:
#    - flutter -v build apk --debug

#task:
#  osx_instance:
#    image: mojave-xcode-10.1
#    image: mojave-xcode-10.2-flutter
#  pub_cache:
#    folder: ~/.pub-cache
#  script: echo "Hello World from macOS!"
#  env:
#    # Name the SDK directory to include a space so that we constantly
#    # test path names with spaces in them.
#    CIRRUS_WORKING_DIR: "/tmp/flutter sdk"
#  setup_script:
#    - bin/flutter config --no-analytics
#    - bin/flutter doctor -v
#    - bin/flutter update-packages
#  build_script:
#    - flutter -v build apk --debug
#    - flutter -v build ios --debug --no-codesign

#task:
#  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
#  pub_cache:
#    folder: ~/.pub-cache
#  depends_on:
#    - analyze
#    - build_tests-macos
#  env:
#    # Name the SDK directory to include a space so that we constantly
#    # test path names with spaces in them.
#    CIRRUS_WORKING_DIR: "/tmp/flutter sdk"
#  osx_instance:
#    image: mojave-xcode-10.1
##    image: mojave-xcode-10.2-flutter
#  # occasionally the clock on these machines is out of sync
#  # with the actual time - this should help to verify
#  print_date_script:
#    - date
#  git_fetch_script:
#    - git clean -xfd
#    - git fetch origin
#    - git fetch origin develop # To set FETCH_HEAD
#  setup_script:
#    - bin/flutter config --no-analytics
#    - bin/flutter update-packages
#    - bin/flutter -v doctor
#  test_all_script:
#    - bin/flutter 
#  build_script:
#    - bin/flutter -v build ios --debug --no-codesign