container:
  image: cirrusci/flutter:latest

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - flutter test
    - flutter doctor

build_task:
  pub_cache:
    folder: ~/.pub-cache
  osx_instance:
    image: mojave-xcode-10.1
  build_script:
#    - flutter -v build apk --debug
    - flutter -v build ios --debug --no-codesign